In [1]:
import seaborn as sns

In [2]:
tips = sns.load_dataset('tips')

In [3]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
# 남자를 1 여자를 2로 하고 싶다면
# map 사용. map은 series에서만 사용 가능
tips.sex.map({'Male':1, 'Female':2})
# 이렇게 딕셔너리 써도 되고 함수 써도 된다

0      2
1      1
2      1
3      1
4      2
5      1
6      1
7      1
8      1
9      1
10     1
11     2
12     1
13     1
14     2
15     1
16     2
17     1
18     2
19     1
20     1
21     2
22     2
23     1
24     1
25     1
26     1
27     1
28     1
29     2
      ..
214    2
215    2
216    1
217    1
218    1
219    2
220    1
221    2
222    1
223    2
224    1
225    2
226    2
227    1
228    1
229    2
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    2
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: int64

In [6]:
tips.sex.map(lambda x : 1 if x == 'Male' else 2 ) # series에 있는 데이터가 하나하나씩 들어간다

0      2
1      1
2      1
3      1
4      2
5      1
6      1
7      1
8      1
9      1
10     1
11     2
12     1
13     1
14     2
15     1
16     2
17     1
18     2
19     1
20     1
21     2
22     2
23     1
24     1
25     1
26     1
27     1
28     1
29     2
      ..
214    2
215    2
216    1
217    1
218    1
219    2
220    1
221    2
222    1
223    2
224    1
225    2
226    2
227    1
228    1
229    2
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    2
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: category
Categories (2, int64): [1, 2]

In [8]:
tips.sex.apply(lambda x : 1 if x == 'Male' else 2)
# map은 series 아니면 DataFrame에서만

0      2
1      1
2      1
3      1
4      2
5      1
6      1
7      1
8      1
9      1
10     1
11     2
12     1
13     1
14     2
15     1
16     2
17     1
18     2
19     1
20     1
21     2
22     2
23     1
24     1
25     1
26     1
27     1
28     1
29     2
      ..
214    2
215    2
216    1
217    1
218    1
219    2
220    1
221    2
222    1
223    2
224    1
225    2
226    2
227    1
228    1
229    2
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    2
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: category
Categories (2, int64): [1, 2]

In [10]:
tips.apply(lambda x : x['total_bill']+x['tip'], axis = 1)
# apply에는 axis 개념이 숨어있다 series 할 때는 map과 동일
# dataframe에서는 조금 더 복잡하게 쓸 수 있다

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
5      30.00
6      10.77
7      30.00
8      17.00
9      18.01
10     11.98
11     40.26
12     16.99
13     21.43
14     17.85
15     25.50
16     12.00
17     20.00
18     20.47
19     24.00
20     22.00
21     23.04
22     18.00
23     47.00
24     23.00
25     20.15
26     15.37
27     14.69
28     26.00
29     22.65
       ...
214    34.67
215    14.00
216    31.15
217    13.09
218     9.18
219    33.23
220    14.36
221    16.90
222    10.50
223    18.98
224    15.00
225    18.77
226    12.09
227    23.45
228    16.00
229    25.00
230    26.01
231    18.69
232    15.00
233    12.24
234    18.53
235    11.32
236    13.60
237    34.00
238    40.50
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [11]:
tips[['total_bill','tip']].apply(lambda x : sum(x))

total_bill    4827.77
tip            731.58
dtype: float64

In [12]:
# apply, applymap만 알면 모든 기능 사용 가능

In [13]:
# for 안 쓰는 애
# 1. 이터,제너
# 2. comprerehension
# 3. 재귀함수
# 4. map/filter/reduce

In [15]:
tips[['total_bill','tip']].applymap(lambda x : x+1) #map과는 비슷하지만 얘는 각각

     total_bill   tip
0         17.99  2.01
1         11.34  2.66
2         22.01  4.50
3         24.68  4.31
4         25.59  4.61
5         26.29  5.71
6          9.77  3.00
7         27.88  4.12
8         16.04  2.96
9         15.78  4.23
10        11.27  2.71
11        36.26  6.00
12        16.42  2.57
13        19.43  4.00
14        15.83  4.02
15        22.58  4.92
16        11.33  2.67
17        17.29  4.71
18        17.97  4.50
19        21.65  4.35
20        18.92  5.08
21        21.29  3.75
22        16.77  3.23
23        40.42  8.58
24        20.82  4.18
25        18.81  3.34
26        14.37  3.00
27        13.69  3.00
28        22.70  5.30
29        20.65  4.00
..          ...   ...
214       29.17  7.50
215       13.90  2.10
216       29.15  4.00
217       12.59  2.50
218        8.74  2.44
219       31.14  4.09
220       13.16  3.20
221       14.42  4.48
222        9.58  2.92
223       16.98  4.00
224       14.42  2.58
225       17.27  3.50
226       11.09  3.00
227       21.45  4.00
228       14.28  3.72
229       23.12  3.88
230       25.01  3.00
231       16.69  4.00
232       12.61  4.39
233       11.77  2.47
234       16.53  4.00
235       11.07  2.25
236       13.60  2.00
237       33.83  2.17
238       36.83  5.67
239       30.03  6.92
240       28.18  3.00
241       23.67  3.00
242       18.82  2.75
243       19.78  4.00

[244 rows x 2 columns]

In [16]:
tips['ratio'] = tips.apply(lambda x:x['tip']/x['total_bill'], axis = 1) # 비율 나온 값 추가

In [17]:
tips

     total_bill   tip     sex smoker   day    time  size     ratio
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
5         25.29  4.71    Male     No   Sun  Dinner     4  0.186240
6          8.77  2.00    Male     No   Sun  Dinner     2  0.228050
7         26.88  3.12    Male     No   Sun  Dinner     4  0.116071
8         15.04  1.96    Male     No   Sun  Dinner     2  0.130319
9         14.78  3.23    Male     No   Sun  Dinner     2  0.218539
10        10.27  1.71    Male     No   Sun  Dinner     2  0.166504
11        35.26  5.00  Female     No   Sun  Dinner     4  0.141804
12        15.42  1.57    Male     No   Sun  Dinner     2  0.101816
13        18.43  3.00    Male     No   Sun  Dinner     4  0.162778
14        14.83  3.02  Female     No   Sun  Dinner     2  0.203641
15        21.58  3.92    Male     No   Sun  Dinner     2  0.181650
16        10.33  1.67  Female     No   Sun  Dinner     3  0.161665
17        16.29  3.71    Male     No   Sun  Dinner     3  0.227747
18        16.97  3.50  Female     No   Sun  Dinner     3  0.206246
19        20.65  3.35    Male     No   Sat  Dinner     3  0.162228
20        17.92  4.08    Male     No   Sat  Dinner     2  0.227679
21        20.29  2.75  Female     No   Sat  Dinner     2  0.135535
22        15.77  2.23  Female     No   Sat  Dinner     2  0.141408
23        39.42  7.58    Male     No   Sat  Dinner     4  0.192288
24        19.82  3.18    Male     No   Sat  Dinner     2  0.160444
25        17.81  2.34    Male     No   Sat  Dinner     4  0.131387
26        13.37  2.00    Male     No   Sat  Dinner     2  0.149589
27        12.69  2.00    Male     No   Sat  Dinner     2  0.157604
28        21.70  4.30    Male     No   Sat  Dinner     2  0.198157
29        19.65  3.00  Female     No   Sat  Dinner     2  0.152672
..          ...   ...     ...    ...   ...     ...   ...       ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3  0.230742
215       12.90  1.10  Female    Yes   Sat  Dinner     2  0.085271
216       28.15  3.00    Male    Yes   Sat  Dinner     5  0.106572
217       11.59  1.50    Male    Yes   Sat  Dinner     2  0.129422
218        7.74  1.44    Male    Yes   Sat  Dinner     2  0.186047
219       30.14  3.09  Female    Yes   Sat  Dinner     4  0.102522
220       12.16  2.20    Male    Yes   Fri   Lunch     2  0.180921
221       13.42  3.48  Female    Yes   Fri   Lunch     2  0.259314
222        8.58  1.92    Male    Yes   Fri   Lunch     1  0.223776
223       15.98  3.00  Female     No   Fri   Lunch     3  0.187735
224       13.42  1.58    Male    Yes   Fri   Lunch     2  0.117735
225       16.27  2.50  Female    Yes   Fri   Lunch     2  0.153657
226       10.09  2.00  Female    Yes   Fri   Lunch     2  0.198216
227       20.45  3.00    Male     No   Sat  Dinner     4  0.146699
228       13.28  2.72    Male     No   Sat  Dinner     2  0.204819
229       22.12  2.88  Female    Yes   Sat  Dinner     2  0.130199
230       24.01  2.00    Male    Yes   Sat  Dinner     4  0.083299
231       15.69  3.00    Male    Yes   Sat  Dinner     3  0.191205
232       11.61  3.39    Male     No   Sat  Dinner     2  0.291990
233       10.77  1.47    Male     No   Sat  Dinner     2  0.136490
234       15.53  3.00    Male    Yes   Sat  Dinner     2  0.193175
235       10.07  1.25    Male     No   Sat  Dinner     2  0.124131
236       12.60  1.00    Male    Yes   Sat  Dinner     2  0.079365
237       32.83  1.17    Male    Yes   Sat  Dinner     2  0.035638
238       35.83  4.67  Female     No   Sat  Dinner     3  0.130338
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]